### ISSUE TITLE
CI: Needs Github Actions

### ISSUE THREAD

**Issue by HaoZeke** [d-SEAMS/PydSEAMSlib#2]
It would be nice to have some automated tests. For starters perhaps just to close this issue, a build test on `ubuntu-latest` would be good.

This is very basic but shows the basic layout:

```yaml
name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildmamba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
      - name: Build
        shell: bash -l {0}
        run: |
          meson setup bbdir
          meson compile -C bbdir
```

Perhaps also a test stage for now. The [official GHA documentation](https://docs.github.com/en/actions) has a lot of advice. Also it is always a good idea to check the workflows used in other projects :)
